# Generated by Django 5.0 on 2024-05-04 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormData',
            new_name='User',
        ),
    ]
