# Generated by Django 5.0 on 2024-04-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='commnet',
            field=models.TextField(default='Not Available'),
        ),
    ]
