# Generated by Django 5.0 on 2024-04-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=70)),
                ('student_email', models.EmailField(max_length=70)),
                ('student_pass', models.CharField(max_length=50)),
            ],
        ),
    ]
